- name: Install Kubernetes binaries
  apt: 
    name="{{ item.name }}"
    state=present
    update_cache=yes
  with_items: "{{ k8s_packages | default([]) }}"

- name: Configure node ip
  lineinfile:
    path: '/etc/systemd/system/kubelet.service.d/10-kubeadm.conf'
    line: 'Environment="KUBELET_EXTRA_ARGS=--node-ip={{ srv_ip }}"'
    regexp: 'KUBELET_EXTRA_ARGS='
    insertafter: '\[Service\]'
    state: present
  notify:
    - restart kubelet

- name: add auto completion kubectl
  command: "{{ item }}"
  with_items:
    - echo 'source <(kubectl completion bash)' >> ~/.bashrc
    - echo 'source <(kubectl completion bash)' >> /home/vagrant/.bashrc
    #- kubectl completion bash > /etc/bash_completion.d/kubectl
  become: true  
  tags:
    - comp

- name: Generate completion command
  command: kubectl completion bash
  register: completion_command
  ignore_errors: true
  tags:
    - comp

- name: Copy comletion commande to the kubectl config file to localhost
  delegate_to: localhost
  copy:
    content: "{{ completion_command.stdout }}"
    dest: ./completion-command  
  tags: comp
  ignore_errors: true  

- name: Copy the completion command to server location
  copy: 
    src: completion-command 
    dest: /etc/bash_completion.d/kubectl 
    mode: 0777
  tags:
    - comp
  ignore_errors: true  